{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.existingSecret }}
type: Opaque
stringData:
  GNMIC_PASSWORD: {{ required "credentials.password is required when credentials.create=true" .Values.credentials.password | quote }}
{{- end }}
